[project]
name = "api-analytics-service"
version = "1.0.0"
description = "Backend for API Analytics"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.1",
    "fastapi[standard]>=0.128.0",
    "sqlalchemy>=2.0.45",
]
